import React, {useEffect,useState} from 'react';
import {DataComponent,EvidenceChart,Section,useDataApp,useDashboardTabs} from '../../data-app-public.jsx';
import './radar.css';

const tabs=[['today','오늘의 판단'],['flows','자금 흐름'],['issues','이슈 추적'],['futures','선물·아시아'],['leverage','신용·미수'],['candidates','종가베팅 후보'],['us','미장 마감'],['review','복기'],['operations','운영·개선']].map(([id,label])=>({id,label}));
const date=v=>!v?'미확보':new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(new Date(v.length===10?v+'T00:00:00Z':v));
const num=(v,d=2)=>v==null?'미확보':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:d});
function remaining(v,now){if(!v)return '시각 미확정';let min=Math.ceil((new Date(v)-now)/60000);if(min<0)return '발표시각 경과·결과 확인 필요';return `${Math.floor(min/60)}시간 ${min%60}분 남음`;}
const Labels={market_kr:'국내 시세',market_us:'미국 시세',futures:'실제 선물',fx:'원달러',asia:'아시아 지수',assets:'주식 외 자산',leverage_kr:'국내 신용·미수',bls:'미국 경제 일정',fomc:'FOMC 일정',holding_calendar:'다음 국내 거래일'};
function Empty({children}){return <div className="radar-empty"><strong>자료 확인 대기</strong><p>{children}</p></div>}
function Badge({children}){return <span className="radar-badge">{children}</span>}
function Table({rows,columns,empty='검증된 자료가 없습니다.'}){return !rows.length?<Empty>{empty}</Empty>:<div className="radar-table-scroll"><table className="radar-table" data-reviewed-rows><thead><tr>{columns.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.ticker||i}>{columns.map(([k,,render])=><td key={k}>{render?render(r):r[k]??'미확보'}</td>)}</tr>)}</tbody></table></div>}
function Card({id,title,q='sources',rows=[],children}){return <DataComponent id={id} title={title} queryId={q} kind="custom" variant="card" sourceRows={rows} displayRows={rows}>{children}</DataComponent>}
function EventList({rows,now}){return rows.length?<div className="radar-events" data-reviewed-rows>{rows.map(e=><article key={e.id} className="radar-event"><div><Badge>{e.severity==='높음'?'주요 발표':e.classification}</Badge><h3>{e.title}</h3><p>{date(e.at)} · {remaining(e.at,now)}</p></div><p>{e.channel}</p><small>{e.time_status||'공식 시각 확인 필요'}</small><a href={e.url||e.source_url} target="_blank" rel="noreferrer">원출처 확인 ↗</a></article>)}</div>:<Empty>현재 수신된 일정에서 선택한 보유구간의 사건을 찾지 못했습니다. 일정 누락과 돌발 사건은 별도 위험입니다.</Empty>}
function Scenarios({rows}){return <div className="radar-grid-three">{rows.map((s,i)=><div className="radar-scenario" key={s.name}><Badge>{s.classification}</Badge><h3>{s.name}</h3><strong>{s.current}</strong><dl><dt>성립 조건·관찰 지표</dt><dd>{s.conditions}</dd><dt>반증 조건</dt><dd>{s.invalidation}</dd><dt>아직 충족하지 못한 조건</dt><dd>국내 시세·선물·환율·후보별 공식 근거 수신과 기준시각 검증</dd><dt>촉발 사건</dt><dd>보유구간의 경제 발표·실적·예상 밖 정책·기업 공시</dd><dt>다음 점검</dt><dd>실제 시세 연결 후 국내 마감·미국 마감·국내 개장 전</dd></dl><small>표본·검증 부족으로 확률과 예상 갭 범위는 제공하지 않습니다.</small></div>)}</div>}
export function DashboardContent(){
 const app=useDataApp();const s=app.snapshot;const r=s.radar||{};const {activeTabId}=useDashboardTabs(tabs);const tab=activeTabId||'today';
 const rows=k=>app.queries[k]?.rows||[];const sources=rows('sources');const events=rows('events');const issues=rows('issues');const rates=rows('rates');const market=rows('markets');const operations=rows('operations');
 const [now,setNow]=useState(Date.now());const [issueScope,setIssueScope]=useState('모두');const [sellTime,setSellTime]=useState(()=>{try{return localStorage.getItem('radar-sell-time')||'09:00'}catch{return '09:00'}});const [venue,setVenue]=useState('KRX');const [holdings,setHoldings]=useState(()=>{try{return localStorage.getItem('radar-local-holdings')||''}catch{return ''}});
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!/^https?:$/.test(location.protocol))return;const id=setInterval(async()=>{try{const response=await fetch(new URL('radar-manifest.json',location.href),{cache:'no-store'});if(!response.ok)return;const m=await response.json();if(m.snapshot_id&&m.snapshot_id!==r.snapshot_id)location.reload()}catch{}},60000);return()=>clearInterval(id)},[r.snapshot_id]);
 function saveTime(v){setSellTime(v);try{localStorage.setItem('radar-sell-time',v)}catch{}}
 function saveHoldings(v){setHoldings(v);try{localStorage.setItem('radar-local-holdings',v)}catch{}}
 const risk=r.risk||{decision:'판단 보류',missing:[],checks:[]};const w=r.window||{};const generated=new Date(s.generatedAt).getTime();const stale=now-generated>30*60000;
 const end=w.next_day&&venue==='KRX'?new Date(`${w.next_day}T${sellTime}:00+09:00`).getTime():null;
 const exposure=end?events.filter(e=>new Date(e.at).getTime()>=generated&&new Date(e.at).getTime()<=end):[];
 const closeTime=r.market_clocks?.KRX?.close;const elapsedHours=end?((end-generated)/36e5).toFixed(1):null;
 const filteredIssues=issues.filter(i=>issueScope==='모두'||i.source_id===issueScope);
 const latest=operations.at(-1)||{};
 return <article className="radar-page">
 <div className="radar-intro"><div><span className="radar-eyebrow">OVERNIGHT MARKET RADAR</span><h1>밤사이 위험을 먼저 확인합니다</h1><p>국내 종가 → 다음 거래일 시초가 · 실제 자료와 조건부 해석을 구분합니다.</p></div><div className="radar-freshness"><Badge>{stale?'갱신 지연 · 판단 보류':risk.decision}</Badge><p>페이지 생성 {date(s.generatedAt)}</p><small>자료별 기준시각은 각 카드에 표시</small></div></div>
 {stale&&<div className="radar-alert" role="status">페이지 생성 후 30분이 지났습니다. 재접속하거나 최신 배포 상태를 확인하세요. 이 화면을 현재 시세로 해석할 수 없습니다.</div>}
 {tab==='today'&&<>
 <Section id="decision-overview" title="지금의 판단" spacing="none">
 <Card id="risk-overview" title="핵심 위험과 판단 보류 이유" rows={sources}><div className="radar-risk"><span className="radar-decision">{risk.decision}</span><div><h2>핵심 데이터를 확보한 뒤 판단하세요</h2><p>{risk.reason}</p><p>누락·미검증: {(risk.missing||[]).map(k=>Labels[k]||k).join(' · ')}</p><small>규칙 {r.method_version} · 검증된 손실확률 아님 · 갭하락 시 손절 가격 체결 보장 없음</small></div></div></Card>
 <div className="radar-grid-three"><Card id="favorable" title="유리한 조건" q="rates" rows={rates}><p>현재 확보 범위에서 종가베팅에 유리하다고 확인할 장중 조건은 없습니다.</p><p>국채금리·일정·공시의 실제 수신은 확인했습니다.</p></Card><Card id="burdens" title="부담되는 조건" q="events" rows={exposure}><strong>관측된 주요 일정 {exposure.length}건 노출</strong><p>돌발 사건·개별 기업 악재·유동성 부족은 예정 일정만으로 배제할 수 없습니다.</p><p>국내·미국 실제 시세와 선물이 미연결입니다.</p></Card><Card id="unknowns" title="아직 모르는 조건" rows={sources.filter(x=>x.status!=='수신 검증 완료')}><p>국내 장후반 수급, 실제 선물 월물, 원달러, 신용·미수, 시간외 반전, 후보별 기업행사.</p><strong>관찰 후보 {(r.candidates||[]).length}개</strong><p>핵심 입력이 부족한 날에는 후보 0개가 정상 결과입니다.</p></Card></div>
 </Section>
 <Section id="holding-settings" title="보유구간과 노출 일정"><Card id="holding-window" title="거래시장·예정 매도시각" q="events" rows={events}><div className="radar-controls"><label>거래시장<select value={venue} onChange={e=>setVenue(e.target.value)}><option value="KRX">KRX 정규장</option><option value="NXT">NXT · 달력 미검증</option></select></label><label>예정 매도시각<input type="time" min="09:00" max="15:30" value={sellTime} onChange={e=>saveTime(e.target.value)}/></label><div><strong>{w.next_day||'다음 거래일 미확인'} {sellTime}</strong><p>{elapsedHours?`현재 관측에서 약 ${elapsedHours}시간 노출`:'선택 시장의 세션·달력 검증 필요'}</p></div></div><p>관측 시작 {date(w.start)} · 국내 마감 {date(closeTime)}. 매도시각 변경은 사건 노출 범위만 바꿉니다. 후보·위험의 서버 판단은 당시 기본 구간을 보존합니다.</p><EventList rows={exposure} now={now}/></Card></Section>
 <Section id="rates-context" title="밤사이 금리 배경"><div className="radar-grid-three">{(r.rate_summary||[]).map(x=><Card key={x.maturity} id={'rate-'+x.maturity} title={'미국 국채 '+x.maturity} q="rates" rows={rates.filter(z=>z.maturity===x.maturity)}><div className="radar-value">{num(x.yieldPct)}<span>%</span></div><p>이전 발표 대비 {x.changeBp>0?'+':''}{num(x.changeBp)} bp</p><p>{x.interpretation}</p><small>기준일 {x.date} · 일별 par yield · 장중 시세 아님<br/><a href="https://home.treasury.gov/treasury-daily-interest-rate-xml-feed" target="_blank" rel="noreferrer">미국 재무부 ↗</a></small></Card>)}</div></Section>
 <Section id="today-scenarios" title="세 가지 조건부 시나리오"><Scenarios rows={r.scenarios||[]}/></Section></>}
 {tab==='flows'&&<>
 <Section id="flow-definitions" title="거래 집중과 실제 자금 흐름" spacing="none"><Card id="flow-explanation" title="이 숫자가 뜻하는 것" q="flows" rows={rows('flows')}><div className="radar-grid-three">{[['거래 집중','동일 시각·시장·종목 범위의 거래대금 점유율. 신규 순유입액이 아닙니다.'],['투자자군 순매수','공식 투자자군 매수−매도. 금액과 수량을 구분합니다.'],['설정·환매 흐름','공식 펀드·ETF 설정·환매 자료. 순자산 증감만으로 대체하지 않습니다.']].map(([a,b])=><div key={a}><h3>{a}</h3><p>{b}</p></div>)}</div><p>상대강도는 선호 변화의 단서입니다. 출발 자산과 도착 자산을 확인하지 못한 자산 간 이동은 가설로 남깁니다.</p></Card></Section>
 <Section id="concentration" title="국내·미국 거래 집중"><Card id="concentration-table" title="관찰 대상 내 업종 비중" q="markets" rows={market}><Table rows={r.concentration||[]} columns={ [['sector','업종'],['market','시장'],['venue','거래소'],['turnover','거래대금',x=>`${num(x.turnover,0)} ${x.currency}`],['turnoverShare','관찰 범위 비중',x=>`${num(x.turnoverShare*100)}%`],['observed_at','기준시각',x=>date(x.observed_at)]] } empty="동일 시각·범위가 검증된 장중 거래대금이 미확보입니다. 국내 원화와 미국 달러를 합산하지 않습니다."/></Card><Card id="measured-flows" title="공식 순매수·설정·환매" q="flows" rows={rows('flows')}><Table rows={rows('flows')} columns={ [['name','대상'],['measurement','측정 항목'],['value','값',x=>`${num(x.value)} ${x.unit}`],['observed_at','기준시각',x=>date(x.observed_at)]] } empty="실제 측정되는 투자자군 순매수·설정·환매 자료는 아직 연결되지 않았습니다."/></Card></Section>
 <Section id="outside-equities" title="주식 밖 자산"><Card id="asset-preference" title="채권·금·달러·원유·가상자산·현금성 자산" q="markets" rows={market}><p>금·달러 상승을 항상 위험회피로 분류하지 않습니다. 채권은 만기별 금리, 원유는 공급·수요를 함께 확인합니다.</p><Table rows={market.filter(x=>x.category==='assets')} columns={ [['name','자산'],['price','가격',x=>`${num(x.price)} ${x.currency}`],['observed_at','기준시각',x=>date(x.observed_at)]] } empty="국채 일별 금리 외 자산 가격·실제 흐름은 미확보. 자산 선호 변화가 관측되더라도 실제 이동 금액과 출발 자산은 별도로 확인해야 합니다."/></Card><EvidenceChart id="treasury-history" queryId="rates" title="미국 국채 만기별 일별 금리" rows={rates} displayRows={rates} sourceRows={rates} spec={{type:'line',x:'date',y:'yieldPct',series:'maturity',yLabel:'금리 (%)',valueDecimals:2,stackable:false,showXAxisLabel:false}} height={320} variant="card"/></Section></>}
 {tab==='issues'&&<Section id="issue-feed" title="원출처에서 확인한 새 사실" spacing="none"><div className="radar-controls"><label>출처<select value={issueScope} onChange={e=>setIssueScope(e.target.value)}><option>모두</option><option value="sec">SEC 공시</option><option value="fed_news">연준 발표</option><option value="research">추가 리서치</option></select></label><p>최근 14일 · SEC 관찰기업 {(r.us_covered||[]).join(', ')||'수신 실패'} · 가격 반응 미검증</p></div><Card id="issue-cards" title="사건·근거·반론·다음 확인" q="issues" rows={filteredIssues}>{!filteredIssues.length?<Empty>해당 범위의 공식 발표·공시 수신을 확인해야 합니다.</Empty>:<div className="radar-issue-list">{filteredIssues.map(i=><article className="radar-issue" key={i.id} data-reviewed-rows><div className="radar-issue-heading"><Badge>{i.classification}</Badge><Badge>{i.state}</Badge><span>{i.scope} · {date(i.at)}</span></div><h3>{i.title}</h3><p>{i.summary}</p><details><summary>시각·전달 경로·반론·다음 점검</summary><dl><dt>최초 발표·공시 접수</dt><dd>{date(i.published_at)}</dd><dt>사건 발생시각</dt><dd>별도 미확인·접수시각으로 대체하지 않음</dd><dt>시스템 최초 확인</dt><dd>{date(i.first_seen_at||i.available_at)}</dd><dt>새 내용</dt><dd>{i.new_content}</dd><dt>전달 경로·기간</dt><dd>{i.channel} · 기간 판단 보류</dd><dt>시장 반응</dt><dd>{i.market_response||i.reaction_status}</dd><dt>반론</dt><dd>{i.counter}</dd><dt>다음 확인</dt><dd>{i.next_check}</dd></dl></details><a href={i.url} rel="noreferrer" target="_blank">공식 원문 ↗</a></article>)}</div>}</Card></Section>}
 {tab==='futures'&&<Section id="futures-asia" title="실제 선물과 아시아 시장" spacing="none"><Card id="futures-table" title="월물·거래소·세션·지연을 확인합니다" q="markets" rows={market}><Table rows={market.filter(x=>x.category==='futures')} columns={ [['contract','계약'],['expiry','월물'],['exchange','거래소'],['session','세션'],['price','가격',x=>num(x.price)],['afterKrCloseChangePct','국내 마감 이후',x=>x.afterKrCloseChangePct==null?'기준값 미확보':num(x.afterKrCloseChangePct)+'%'],['observed_at','시세시각',x=>date(x.observed_at)],['delay_status','지연']] } empty="코스피200·나스닥100·S&P500 실제 선물 데이터 미확보. 현물지수·ETF를 실제 선물로 표시하지 않습니다."/></Card><Card id="asia-table" title="일본·중국·홍콩·대만 · 환율·금리" q="markets" rows={market}><Table rows={market.filter(x=>['asia','fx'].includes(x.category))} columns={ [['name','지표'],['venue','거래소'],['price','값',x=>num(x.price)],['observed_at','기준시각',x=>date(x.observed_at)]] } empty="아시아 지수·원달러 장중 시세 미연결. 거래소별 휴일·점심휴장·선물 중단은 피드 연결 후 함께 검증해야 합니다."/><p>전일 대비 변화와 국내 정규장 마감 이후 변화는 다른 기준입니다. 만기·롤오버·연속선물 조정도 분리해야 합니다.</p></Card></Section>}
 {tab==='leverage'&&<Section id="leverage-analysis" title="신용·미수·반대매매" spacing="none"><Card id="leverage-table" title="과열 배경과 가격 하락 시 취약성" q="leverage" rows={rows('leverage')}><Table rows={rows('leverage')} columns={ [['name','통계'],['value','값',x=>`${num(x.value)} ${x.unit}`],['reference_date','발표 기준일'],['definition','정의'],['denominator_definition','분모']] } empty="금융투자협회 공식 통계의 자동수집·공개 조건을 확인하지 못했습니다. 잔고·미수·실제 반대매매는 미확보이며 0으로 표시하지 않습니다."/><details><summary>분석 기준과 한계</summary><p>충분한 과거 기간의 백분위, 시장 규모 대비 비율, 신용·예탁금 관계를 확인해야 합니다. 절대 잔고만으로 하락을 예측하거나 시장 전체 통계로 특정 종목의 반대매매를 확정할 수 없습니다.</p><p>잔고 증가 속도는 과열 배경, 변동성·실제 반대매매는 하락 시 취약성으로 나눕니다. 현재 이 계산에 필요한 역사 자료는 미확보입니다.</p></details></Card></Section>}
 {tab==='candidates'&&<><Section id="candidate-selection" title={`관찰 후보 ${(r.candidates||[]).length}개`} spacing="none"><Card id="candidate-comparison" title="핵심 위험이 있으면 판단 보류를 우선합니다" q="markets" rows={market}><Table rows={r.candidates||[]} columns={ [['name','종목'],['reason','선정 근거'],['turnover','거래대금',x=>num(x.turnover,0)+'원'],['observed_at','당시 기준시각',x=>date(x.observed_at)]] } empty="현재는 국내 장중 시세·선물·환율·기업행사 확인이 부족해 후보를 제시하지 않습니다. 관망과 후보 0개를 정상 결과로 보존합니다."/><details><summary>후보 기준·제외 이유</summary><p>기본 국내 보통주, 최대 5개. 충분한 유동성·가격 위치·공식 촉매·기업행사 검증이 필요합니다. ETF·ETN·스팩·우선주·거래정지·정리매매는 기본 제외합니다.</p><p>운영 임시 기준: 거래대금 100억원 이상, 당일 상승률 20% 이하, 장중 가격 위치 0.7 이상, 핵심 시세 15분 이내. 수익률로 검증된 기준은 아닙니다.</p></details><Table rows={r.excluded||[]} columns={ [['name','제외 종목'],['reasons','제외·보류 이유']] } empty="시세 관찰 범위가 아직 없으므로 종목별 제외 목록도 생성하지 않았습니다."/></Card></Section><Section id="candidate-scenarios" title="시장 공통 시나리오"><Scenarios rows={r.scenarios||[]}/></Section><Section id="local-watchlist" title="내 관찰종목 메모"><Card id="local-holdings" title="이 기기에만 저장하는 메모" rows={[]}><label className="radar-local-label">종목·예정 매도시각·확인할 공시<textarea value={holdings} onChange={e=>saveHoldings(e.target.value)} placeholder="개인 관찰종목 메모"/></label><small>브라우저 로컬 저장. 서버·공개 저장소로 전송하지 않습니다. 이 메모는 자동 종목 위험 분석에 연결되어 있지 않습니다.</small></Card></Section></>}
 {tab==='us'&&<Section id="us-briefings" title="미국 정규장 마감 브리핑" spacing="none"><Card id="us-close-list" title="실제 거래소 마감과 확정 자료를 확인한 뒤 기록" q="issues" rows={issues}>{!(r.briefings||[]).length?<Empty>아직 검증된 마감 후 브리핑이 없습니다. 미국 조기폐장·서머타임·휴장 달력과 실제 시세 확정 여부를 따로 확인합니다.</Empty>:(r.briefings||[]).slice().reverse().map(b=><article className="radar-issue" key={b.date}><Badge>{b.status}</Badge><h3>{b.date} 미국 마감</h3><p>{b.summary}</p><p>{b.scope}</p><small>실제 예정 정규장 종료 {date(b.exchange_close)} · 생성 {date(b.available_at)}</small><p>{b.next_check}</p></article>)}<p>공시 관찰 10개 기업은 미국 전체 상위 종목 범위가 아닙니다. 정규장·시간외 반전 및 국내 공급망 연결은 별도 근거가 필요합니다.</p></Card></Section>}
 {tab==='review'&&<Section id="daily-review" title="당시 판단과 다음 거래일 결과" spacing="none"><Card id="review-table" title="후보 0개·실패·제외 이유도 보존합니다" q="diary" rows={rows('diary')}><Table rows={rows('diary')} columns={ [['date','판단일'],['available_at','당시 시각',x=>date(x.available_at)],['candidates','후보 수',x=>x.candidates?.length??0],['risk','당시 판단',x=>x.risk?.decision||'미확인'],['result','다음 거래일 결과']] } empty="첫 마감 전 실행을 기다리고 있습니다. 15:10~15:29에 실제 수집된 당시 판단만 저장하며 마감 후 값으로 소급 생성하지 않습니다."/><p>시가·후속 가격·기업행사 자료가 없는 날에는 실제 갭·전략 수익을 계산하지 않습니다. 역사 자료·시간 순 검증 전 확률 보정이나 가중치 개선은 적용하지 않습니다.</p></Card></Section>}
 {tab==='operations'&&<>
 <Section id="pipeline-state" title="운영 상태와 실제 수신 검증" spacing="none"><Card id="operation-summary" title="갱신·누락·배포 확인" q="operations" rows={operations}><div className="radar-grid-three"><div><h3>최근 수집</h3><p>{date(latest.started_at)}</p><strong>{num(latest.seconds)}초 · {num(latest.calls,0)}회 요청</strong></div><div><h3>놓친 수집 슬롯</h3><strong>{num(latest.missed_slots,0)}개</strong><p>과거 값을 조회할 수 없으면 공백을 보존합니다.</p></div><div><h3>공개 배포</h3><strong>공개 URL 검증 대기</strong><p>Actions 성공만으로 완료하지 않습니다.</p></div></div><details><summary>실행·빌드 식별자</summary><dl><dt>코드 commit</dt><dd className="radar-code">{r.source_commit}</dd><dt>데이터 스냅샷</dt><dd className="radar-code">{r.snapshot_id}</dd><dt>분석 버전</dt><dd>{r.method_version}</dd><dt>현재 실패</dt><dd>{latest.failures?.join(' · ')||'이번 공개 소스 수집 실패 없음'}</dd></dl></details><p>10분은 Actions 실행 목표입니다. 예약 지연·누락·60일 무활동 중단에 대한 독립 감시가 아직 없고 정확한 정시는 보장하지 않습니다.</p></Card><Card id="source-register" title="데이터별 제공 범위·지연·인증·비용" rows={sources}><div className="radar-source-list">{sources.map(e=><details key={e.id}><summary><strong>{e.name}</strong><Badge>{e.status}</Badge></summary><dl>{[['제공기관',e.provider],['필드',e.fields],['주기·지연',e.frequency+' · '+e.delay],['실제 수신',`${e.row_count}개 · ${date(e.checked_at)} · 기준 ${e.last_data_date||'미확보'}`],['인증',e.authentication],['비용·한도',e.cost+' · '+e.rate_limit],['보관·공개',e.publication],['대체 출처',e.alternative]].map(([a,b])=><React.Fragment key={a}><dt>{a}</dt><dd>{b}</dd></React.Fragment>)}</dl><a href={e.documentation} target="_blank" rel="noreferrer">공식 안내 ↗</a></details>)}</div></Card></Section>
 <Section id="setup-help" title="사용자 도움이 필요한 연결"><Card id="help-register" title="한곳에 모은 연결 작업" rows={sources}><Table rows={r.help||[]} columns={ [['name','필요 기능'],['task','정확한 작업'],['secret','Secret 이름'],['cost','예상 비용'],['url','공식 안내',x=><a href={x.url} target="_blank" rel="noreferrer">설정 안내 ↗</a>]] }/><p>키는 GitHub 저장소 Settings → Secrets and variables → Actions에 저장합니다. 시세 공개 권한 확인 전 publication_approvals를 켜지 마세요. 연결 후 실제 응답·기준시각·세션·공개 URL을 검증해야 해결 처리합니다.</p></Card></Section>
 <Section id="costs-improvements" title="예산과 다음 개선"><Card id="budget" title="실행량과 비용" q="operations" rows={operations}><p>24시간 10분 목표: 하루 144회, 30일 4,320회. 회당 3분 가정 시 월 12,960 러너분, 각 실행 8분 제한. 실제 월 누적 비용은 GitHub 사용량에서 확인해야 합니다.</p><p>기본 LLM API 비용 0원. ChatGPT 구독과 API 요금은 별개입니다. 유료 시세·공개 재배포 비용은 계약 확인이 필요합니다.</p><p>다음 우선순위: 실제 국내·선물 시세 권한 → 국내 공시·기업행사 → 신용 통계 → 해외 시간외·공식 펀드 흐름 → 충분한 역사 데이터와 복기.</p><p>범위 밖 개선: 독립 외부 스케줄러·가동 감시(정시성·장애 탐지, 서비스 비용·계정 필요), 알림 채널(위험 변동 알림, 사용자 채널 연결 필요). 자동 주문은 포함하지 않습니다.</p></Card></Section></>}
 <footer className="radar-footer"><strong>사실 · 해석 · 조건부 시나리오 · 미확인</strong><p>자료가 부족하면 판단을 보류합니다. 거래대금은 신규 자금 유입이 아니며, 자산 간 가격 움직임만으로 같은 돈의 이동을 확정하지 않습니다.</p><small>시가 갭은 선택 시장의 전일 정규장 종가와 다음 정규장 시가 기준 · 국내 거래일 확인 범위 2026년 10월 · 관측 {date(s.generatedAt)}</small></footer>
 </article>
}
